clearKits:
  onDisable: true
  onDeath: true
  onDisconnect: true
  
#If this is not set to false, KitMaster will automatically update itself from the latest file on BukkitDev
automaticallyUpdate: true