clearKits:
  onDeath: true
  onDisable: false
  onDisconnect: false
  
#If this is not set to false, KitMaster will automatically update itself from the latest file on BukkitDev
automaticallyUpdate: true