clearKits:
  onDeath: true
  onDisable: false
  onDisconnect: false
inventory:
  autoEquipWeapon: true
  autoEquipArmor: true
  woolHats: false
  skullHats: false
  renameFireworks: true
maxStacks:
  Potion: 16
automaticallyUpdate: true