main: com.amoebaman.kitmaster.KitMaster

name: KitMaster
version: 1.0 (1.4.5)
author: AmoebaMan
description: The complete kit plugin
softdepend: [Vault]

commands:

  givekit:
    description: Give a kit to a player
    usage: /givekit <player> <kit-name>
    permission: kitmaster.give
    permission-message: You dont have permission to give kits

  kit:
    description: Get a kit
    usage: /kit <kit-name>
    permission: kitmaster.cmd
    permission-message: You don't have permission to take kits via command

  kitlist:
    description: List the available kits
    usage: /kitlist
    permission: kitmaster.list
    permission-message: You don't have permission to view kits

  kitinfo:
    description: Displays info about a kit
    usage: /kitinfo <kit>
    permission: kitmaster.info
    permission-message: You don't have permissions to get info about kits

  reloadkits:
    description: Reloads kits from kits.yml
    usage: /reloadkits
    permission: kitmaster.reload
    permission-message: You don't have permission to reload kits

  savebook:
    description: Save the held book to a file
    usage: /savebook <name>
    permission: kitmaster.books
    permission-message: You don't have permission to manage books

  loadbook:
    description: Loads the book with the given title
    usage: /loadbook <name>
    permission: kitmaster.books
    permission-message: You don't have permission to manage books

permissions:

  kitmaster.*:
    description: Gives access to all SuperKits permissions
    children:
      kitmaster.give: true
      kitmaster.cmd: true
      kitmaster.list: true
      kitmaster.info: true
      kitmaster.reload: true
      kitmaster.kit.*: true
      kitmaster.notimeout: true
      kitmaster.nocharge: true
      kitmaster.createsign: true
    
  kitmaster.cmd:
    description: Allows the player to take kits by command
    default: true
    
  kitmaster.sign:
    description: Allows the player to take kits from signs
    default: true
    
  kitmaster.respawn:
    description: Allows the player to automatically take kits when then respawn
    default: true
    
  kitmaster.list:
    description: Allows the player to see the kits available to them
    default: true
    
  kitmaster.info:
    description: Allows the player to see the contents and options of any kit available to them
    default: true
    
  kitmaster.give:
    description: Allows the player to give kits to other players
    default: op
    
  kitmaster.reload:
    description: Allows the player to reload the kits file
    default: op
    
  kitmaster.kit.*:
    description: Grants permission for all kits
    default: op
    
  kitmaster.shorttimeout:
    description: Reduces the timeouts of all kits (except global-timeouts) to 1/3 their configured values for the player
    default: false
    
  kitmaster.notimeout:
    description: Removes the timeouts of all kits entirely for the player
    default: op
    
  kitmaster.nocharge:
    description: Removes any economic costs/grants from kits for the player
    default: op
    
  kitmaster.createsign:
    description: Allows the player to create and break kit selection signs
    default: op
    
  kitmaster.books:
    description: Allows the player to save and load books
    default: op