main: net.amoebaman.kitmaster.KitMaster

name: KitMaster
version: 1.3
author: AmoebaMan
description: The complete kit plugin
softdepend: [Vault]

commands:

  kit:
    description: Get a kit
    usage: /kit <kit-name>
    permission-message: You don't have permission to take kits via command

  givekit:
    description: Give a kit to a player
    usage: /givekit <player> <kit-name>
    permission: kitmaster.give
    permission-message: You dont have permission to give kits

  kitlist:
    description: List the available kits
    usage: /kitlist
    permission: kitmaster.list
    permission-message: You don't have permission to view kits

  kitinfo:
    description: Displays info about a kit
    usage: /kitinfo <kit>
    permission: kitmaster.info
    permission-message: You don't have permissions to get info about kits

  reloadkits:
    description: Reloads kits from kits.yml
    usage: /reloadkits
    permission: kitmaster.reload
    permission-message: You don't have permission to reload kits
    
  itemmeta:
    aliases: [meta, metadata]
    description: Base for various item metadata manipulation commands
    usage: /itemmeta ...
    permission: kitmaster.meta
    permission-message: You don't have permission to manage item metadata
    
  editkit:
    aliases: [kitedit, kedit, editk]
    description: Base for various kit editing commands
    usage: /editkit ...
    permission: kitmaster.edit
    permission-message: You don't have permission to edit kits

permissions:

  kitmaster.*:
    description: Gives access to all SuperKits permissions
    children:
      kitmaster.give: true
      kitmaster.list: true
      kitmaster.info: true
      kitmaster.reload: true
      kitmaster.kit.*: true
      kitmaster.notimeout: true
      kitmaster.nocharge: true
      kitmaster.createsign: true
      kitmaster.books: true
      kitmaster.fireworks: true
    
  kitmaster.sign:
    description: Allows the player to take kits from signs
    default: true
    
  kitmaster.respawn:
    description: Allows the player to automatically take kits when then respawn
    default: true
    
  kitmaster.list:
    description: Allows the player to see the kits available to them
    default: true
    
  kitmaster.info:
    description: Allows the player to see the contents and options of any kit available to them
    default: true
    
  kitmaster.give:
    description: Allows the player to give kits to other players
    default: op
    
  kitmaster.reload:
    description: Allows the player to reload the kits file
    default: op
    
  kitmaster.kit.*:
    description: Grants permission for all kits
    default: op
    
  kitmaster.shorttimeout:
    description: Reduces the timeouts of all kits (except global-timeouts) to 1/3 their configured values for the player
    default: false
    
  kitmaster.notimeout:
    description: Removes the timeouts of all kits entirely for the player
    default: op
    
  kitmaster.nocharge:
    description: Removes any economic costs/grants from kits for the player
    default: op
    
  kitmaster.createsign:
    description: Allows the player to create and break kit selection signs
    default: op
    
  kitmaster.books:
    description: Allows the player to save and load books
    default: op
    
  kitmaster.fireworks:
    description: Allows the player to save and load fireworks
    default: op
    
  kitmaster.meta:
    description: Allows the player to manage item metadata
    default: op
    
  kitmaster.edit:
    description: Allows the player to edit kits
    default: op
    